- adtl/__init__.py
- docs/specification.md
- tests/test_parser.py
Using string quoted null and falsy can be confused with the
similar unquoted null and false values that are valid JSON.
> Rename exclude to excludeWhen, use null / false

- .gitignore
- adtl/__init__.py
Fixes errors where either an empty string is passed to pint, or a source unit has not been provided
> get_value_unhashed: use default units if not set

- adtl/__init__.py
- docs/specification.md
- tests/parsers/constant.json
- tests/parsers/groupBy-defs.json
- tests/parsers/groupBy-incorrect-aggregation.json
- tests/parsers/groupBy-missing-kind.json
- tests/parsers/groupBy-missing-table.json
- tests/parsers/groupBy.json
- tests/parsers/oneToMany.json
- tests/test_parser.py
TOML does not support # in bare keys, removing them for simplicity.
Also moves metadata (name/description/tables/defs) into an adtl
header to free up top level namespace for table assignments.
> Move header into adtl key, remove # in defs/refs/if

- adtl/__init__.py
- tests/__snapshots__/test_parser.ambr
Dictionaries do not have a defined key order, sorting ensures
runs are reproducible.
> Sort output fields for reproducibility

- adtl/__init__.py
- tests/parsers/apply.toml
- tests/test_parser.py
Some of the recent changes broke the apply functionality by filtering out empty string entries which are required by functions like 'isNotNull'. Fixed this and added tests for the apply functionality itself to check for this in future.
> Added tests for apply functionality

- adtl/__init__.py
- docs/specification.md
- tests/__snapshots__/test_parser.ambr
- tests/test_parser.py
Attempt to cast strings into integers or floats if possible, and return cast values instead of strings.
This is a **breaking change** as previously all get_value() results that were not a container type were either booleans or strings.
Also fixes a bug in if parsing for oneToMany tables
> Fix oneToMany if bug, cast into numeric types when possible

- adtl/transformations.py
- tests/test_transformations.py
Strips additional whitespace and quotes to allow float conversion.
Reduces number of 'data.value must be float' errors
> Add getFloat to remove chars from numerical fields

- adtl/__init__.py
- adtl/transformations.py
- docs/specification.md
- tests/parsers/oneToMany-missingIf.toml
- tests/schemas/observation_defaultif.schema.json
- tests/sources/oneToManyIf-missing.csv
- tests/sources/oneToManyIf.csv
- tests/test_parser.py
- tests/test_transformations.py
* Added endDate to calculate dates given a start date and duration (for Washington dataset)
* Bug-fixed firstNonNull which wasn't recognising 'False' as a valid non-Null value
* Add default `if' behaviour for the oneToMany table, removing requirement for if statements in the parser if you only want to (1) not show empty strings, or (2) have a set of values mapped and don't want to show those outside that mapping.
> Add endDate, auto-if behaviour in oneToMany table

- adtl/__init__.py
- tests/__snapshots__/test_parser.ambr
- tests/parsers/groupBy-with-schema.json
- tests/test_parser.py
When aggregating on a group key, value was assigned to a attribute
if it was not null. The null element for a list is [], which is not
None, and this led to overwriting the previous non-null values.
> Fix combinedType=set,list aggregation by group key

- adtl/transformations.py
fixes problem where duration is being read in as a string rather than a float
> Patch for endDate

- adtl/__init__.py
- docs/specification.md
- tests/parsers/apply.toml
Previously, constant strings were interpreted as field names when
using apply. This changes the behaviour to require $ prefix to
indicate the following token is a field name.
> Allow constant strings in apply parameters

- adtl/__init__.py
- pyproject.toml
- tests/test_parser.py
Prior to this change, combinedType = any/all would return False if
all the values in the list were None. In most cases, datasets have
all values None when data is missing, and in that case, assuming
negative when data is missing is inconsistent with the mapping for
single fields.
In addition, for the clinical applications that are being used,
value mappings are better imagined as open-world (absence of a
statement does not imply falsity) rather than closed-world, where
the absence of a statement means it is false. As an example, for
medication mappings, it is possible we have missed out a medication
in the antibiotics list, so the absence does not imply that a
patient did not receive that category of medication, in this case,
antibiotics. In general, we are more certain that something …
> BREAKING CHANGE: any and all return None if all values are None

- adtl/__init__.py
- docs/specification.md
- schemas/dev.schema.json
- tests/__snapshots__/test_parser.ambr
- tests/parsers/oneToMany-missingIf.toml
- tests/parsers/skip_field.json
- tests/schemas/epoch-data.schema.json
- tests/schemas/observation_defaultif.schema.json
- tests/sources/oneToManyIf.csv
- tests/sources/skip_field_absent.csv
- tests/sources/skip_field_present.csv
- tests/test_parser.py
This PR allows certain fields, or field patterns, to be skipped if not present in the data, to use when a single study has multiple datasets with a varying amount of data entry.
> Skip fields

- adtl/__init__.py
- adtl/transformations.py
- tests/sources/oneToManyIf-missingError.csv
- tests/test_parser.py
- tests/test_transformations.py
Changes getFloat behaviour to force explicit definition of the decimal/thousand separator to stop unwanted conversation of normal floats (e.g. prior behaviour converted "3.4" -> 34)
Expands various tests & fixes a few bugs
> Add exception tests

- adtl/__init__.py
- tests/test_parser.py
Fixes where apply was being used with a parameter list of ints/floats, the for loop expansion crashed as it only expected str/dict options.
> Fixes behaviour where for loops combine with apply

- adtl/transformations.py
- tests/test_transformations.py
E.g. sometimes scales like sedation scales are filled in as a mix of numbers and '-3 moderate sedation' etc. Want to be able to scrape out the value in these cases.
> Allow 'getFloat' to scrape a number from a string with other text

- adtl/transformations.py
- tests/test_transformations.py
Dates aren't formatted before going into apply functions - this allows yearsElapsed to have the input (particularly where the parameter is a field) date format specified.
> allow date formats to be specifed in yearsElapsed function

- .coveragerc
- adtl/__init__.py
- adtl/transformations.py
- pyproject.toml
- tests/__snapshots__/test_parser.ambr
- tests/parsers/epoch-web-schema.json
- tests/parsers/epoch.yml
- tests/parsers/oneToMany-commonMappings.json
- tests/test_parser.py
Add test dependency on responses to test requests calls
> Increase test coverage

- adtl/__init__.py
- docs/specification.md
- pyproject.toml
- tests/test_parser.py
- Add =~ regex comparison operator
- Bump version, update authors
> add regexMatch

- adtl/__init__.py
- pyproject.toml
- tests/schemas/epoch-oneOf.schema.json
- tests/test_parser.py
Edits "anyOf" required fields to match the optional-fields requirements
> Add "anyOf" to optional fields validation

- adtl/__init__.py
- adtl/transformations.py
- docs/specification.md
- tests/__snapshots__/test_parser.ambr
- tests/parsers/return-unmapped.toml
- tests/sources/return-unmapped.csv
- tests/test_parser.py
Add setting to return values when they aren't converted or mapped.
> Add returnUnmatched to spec options

- .github/workflows/black.yml
- .github/workflows/tests.yml
- README.md
- pyproject.toml
Adds upper limit on requires-python (temporary, only until pint error is resolved)
Adds red label for python 3.13
> Mark 3.13 as unsupported

- src/adtl/autoparser/dict_writer.py
- tests/test_autoparser/sources/animals_dd_described.csv
Whether or not an LLM was used to generate descriptions.
Fixes #118
> Data dictionary headers returned in same format

- docs/autoparser/examples/cli_example.md
- docs/autoparser/examples/example.ipynb
- docs/autoparser/getting_started/index.md
- docs/autoparser/usage/parser_generation.md
- docs/index.md
- src/adtl/autoparser/dict_writer.py
- src/adtl/autoparser/language_models/gemini.py
- src/adtl/autoparser/language_models/openai.py
- src/adtl/autoparser/mapping.py
- src/adtl/autoparser/util.py
- tests/test_autoparser/test_dict_writer.py
- tests/test_autoparser/test_gemini.py
- tests/test_autoparser/test_mapper.py
- tests/test_autoparser/test_openai.py
- tests/test_autoparser/test_utils.py
Adds the ability for a user to select which LLM model (from the openai or gemini range) they wish to use, while keeping `gpt-4o-mini` and `gemini-1.5-flash` as the defaults.
> Add model choice

- docs/specification.md
- src/adtl/__init__.py
- src/adtl/parser.py
- src/adtl/python_interface.py
- tests/test_adtl/parsers/stop-overwriting.toml
- tests/test_adtl/test_parser.py
Fixes #135 
Creates a *lastNotNullStrict* and sets up structure to allow *x*/*xStrict* aggregation types for future use.
Adds to the specification to explain combinedType will apply over grouped rows if non-strict aggregation is selected.
> Aggregation

- docs/specification.md
- src/adtl/get_value.py
- src/adtl/parser.py
- src/adtl/util.py
- tests/test_adtl/parsers/test.schema.json
- tests/test_adtl/schemas/epoch-data.schema.json
- tests/test_adtl/test_util.py
Fixes #153 
Where a type is specified for a field in a schema, ADTL will attempt to coerce any returned value to that type. In the case of float -> int where there are non-zero decimals, the float will be rounded.
> Type coercion
